timezone: Pacific Standard Time (PST)
tabs:
- title: ""
  contents:
    - time: Jan. 1, 2025
      title: Application opens for both workshops
      description: null
    - time: Feb. 28, 2025
      title: Application closes for Seattle workshop
      description: null
    - time: Mar. 31, 2025
      title: Application closes for New Orleans workshop
      description: null
